### PR TITLE
Batteries

### PR DESCRIPTION
**Pull request by IonicaBizau**
I bought an accumulator which works so nice! :joy: /cc @lcristianiim

### CODE REVIEW

**Comment by lcristianiim** [comment]
Niceeeeee! :battery: 
What autonomy do you have?

**Comment by IonicaBizau** [comment]
It has ~10Ah and my pi uses about one amper. Does that mean it will live for ~10 hours? :smile: I will test it out and see. I will discharge it completely.

**Comment by lcristianiim** [comment]
Yeah it should be 10 hours. Let me know the running time. :watch:  :racehorse:

**Comment by IonicaBizau** [comment]
Okkk, so it was alive for **almost 19 hours** (from 9PM to 3:40PM). :sparkles: I made a little script to keep it busy, kind of: `watch date >> log`

Quite impressive. I'm so happy with it. :smile:

**Pull request merged**
